name: AutoGphotoPatch13
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Framework.jar Url'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setting up
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget default-jdk android-sdk-libsparse-utils zip aapt unzip axel python3-pip zipalign apksigner xmlstarlet
        pip3 install ConfigObj

    - name: JAVA setup
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '21'

    - name: Set up Time
      run: |
        cd $GITHUB_WORKSPACE
        echo "Setting Vietnam timezone"
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh

    - name: Download Framework.jar
      run: |
        axel -n $(nproc) "${{ github.event.inputs.ROM_URL }}"

    - name: PATCH-ING
      run: |
        sudo chmod 777 -R *
        ./vanilla13.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: framework13.zip
        path: ./module/*
