name: AutoGphotoPatch13
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Framework.jar Url'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setting up
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget whiptail cpio bc android-sdk-libsparse-utils zip aapt unzip axel python3 python3-pip bc zipalign apksigner jq xmlstarlet p7zip-full
        pip3 install ConfigObj
        
    - name: JAVA setup
      run: |
        sudo apt-get install -y openjdk-11-jre
        
    - name: Set up Time
      run: |
        cd $GITHUB_WORKSPACE
        echo "Setting Vietnam timezone"
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh

    - name: Download Framework.jar
      run: |
        axel -n $(nproc) "${{ github.event.inputs.ROM_URL }}"

    - name: PATCH-ING
      env:
        JAVA_OPTS: -Xmx4096m
      run: |
        sudo chmod 777 -R *
        sudo bash vanilla13.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: framework13.zip
        path: ./module/*
