name: AutoGphotoPatch13

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Framework.jar Url'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.8.5-openjdk-11  # Pre-built Docker image with Java 11

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting up (within container)
        run: |
          apk add --no-cache git wget whiptail cpio bc openjdk11-jre zip unzip axel python3 python3-pip bc zipalign apksigner jq xmlstarlet p7zip-full
          pip3 install ConfigObj

      - name: Download Framework.jar (within container)
        run: |
          axel -n $(nproc) "${{ github.event.inputs.ROM_URL }}"

      - name: PATCH-ING (within container)
        env:
          JAVA_OPTS: -Xmx4096m
        run: |
          chmod 777 -R * 
          ./vanilla13.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: framework13.zip
          path: ./module/*
