name: AutoGphotoPatch13
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Framework.jar Url'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Clean Junks
      run: |
        docker rmi `docker images -q` || true
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
        sudo apt -y autoremove --purge || true
        sudo apt -y autoclean || true
        sudo apt clean || true

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 8192
        root-reserve-mb: 4096
        temp-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    
    - name: Checkout
      uses: actions/checkout@main

    - name: Setting up
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget default-jdk android-sdk-libsparse-utils zip aapt unzip axel python3-pip bc zipalign apksigner xmlstarlet python3 
        pip3 install ConfigObj

    - name: JAVA setup
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        java-package: 'jdk' 'jre'

    - name: Set up Time
      run: |
        cd $GITHUB_WORKSPACE
        echo "Setting Vietnam timezone"
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh

    - name: Download Framework.jar
      run: |
        axel -n $(nproc) "${{ github.event.inputs.ROM_URL }}"

    - name: PATCH-ING
      env:
        JAVA_OPTS: -Xmx4096m
      run: |
        sudo chmod 777 -R *
        sudo bash vanilla13.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: framework13.zip
        path: ./module/*
